{% set name = "aioshutil" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aioshutil-{{ version }}.tar.gz
  sha256: 2756d6cd3bb03405dc7348ac11a0b60eb949ebd63cdd15f56e922410231c1201

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - typing-extensions

test:
  imports:
    - aioshutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kumaraditya303/aioshutil
  summary: Asynchronous shutil module.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ivergara
